### ISSUE TITLE
Error 403 on using imgNotes in existing project

### ISSUE THREAD

**Issue by ritikajagtiani** [waynegm/imgNotes#25] opened 2016-11-11 14:53 UTC
It is giving error 403 if I use this image note in my existing project, even if I place the imgNotes.js and imgViewer.js at correct location of my existing project. Internally, it is using some file at some fixed path, please allow user to customize it as per their existing  project to get rid of 403

**Comment by waynegm** [comment] 2016-11-12 07:42
Any chance you can give me some more to go on.  Maybe show me a simple example html file that creates the error.

The only external reference in the plugins is in the default onAdd callback which users can redefine. Even that reference is just to a css class for the note marker which should work if you have included the css in your html file.

**Comment by ritikajagtiani** [comment] 2016-11-14 00:26
Hi Wayne,

Following is the code snippet and situation:
1. Layout code - added all the requisite js here:

<meta name="description" content="Dashboard" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon"
href="${resource(dir:'assets/img',file:'EasyTox.png')}">




<link rel="stylesheet" href="${resource(dir:'css',file:'marker.css')}" />

<script src="${resource(dir:'js',file:'jquery.js')}" type="text/javascript"
></script>
<script src="${resource(dir:'js',file:'jquery-loader.js')}"
type="text/javascript" ></script>
<script src="${resource(dir:'js',file:'jquery-ui.js')}"
type="text/javascript" ></script>
<script src="${resource(dir:'js',file:'jquery-ui-loader.js')}"
type="text/javascript" ></script>
<script src="${resource(dir:'js',file:'jquery.fs.zoetrope.min.js')}"
type="text/javascript"></script>
<script src="${resource(dir:'js',file:'hammer.min.js')}"
type="text/javascript"></script>
<script src="${resource(dir:'js',file:'jquery.hammer.js')}"
type="text/javascript"></script>
<script src="${resource(dir:'js',file:'jquery.mousewheel.min.js')}"
type="text/javascript"></script>
<script src="${resource(dir:'js',file:'printThis.js')}"
type="text/javascript"></script>

<script src="${resource(dir:'js',file:'imgViewer.min.js')}"
type="text/javascript"></script>
<script src="${resource(dir:'js',file:'imgViewer-loader.js')}"
type="text/javascript" ></script>
<script src="${resource(dir:'js',file:'imgNotes.js')}"
type="text/javascript"></script>


<link
href="${resource(dir:'beyondadmin/html/assets/css',file:'bootstrap.min.css')}"
rel="stylesheet" />
<link
href="${resource(dir:'beyondadmin/html/assets/css',file:'font-awesome.min.css')}"
rel="stylesheet" />
<link
href="${resource(dir:'beyondadmin/html/assets/css',file:'weather-icons.min.css')}"
rel="stylesheet" />



2. Form to add the image:

<form class="form-horizontal" id="imageform" role="form"
enctype="multipart/form-data" action='save' method="POST">
<input type="hidden" name="caseDocumentID" id="caseDocumentID"
value="${caseDocumentInstance?.caseDocumentID}">
<g:set var="client" bean="clientService" />
<table id="tblImgDocSample" class="table">
<thead>
<tr>
<th width="5%"></th>
<th width="20%">Image</th>
<th width="20%">Image Type</th>
<th width="15%">Date Added</th>
<th width="10%">Caption</th>
<th width="15%">Comments</th>
<th width="15%"></th>
</tr>
</thead>
<tbody>
Add Image
<tr>
<td></td>
<td><div class="form-group">
<div class="col-sm-10">
<input type="file" id="documentData" name="documentData"
class="form-control" />

</div>
</div></td>
<td><div class="form-group">
<div class="col-sm-8">
<g:select id="documentType" name="documentType" value="jpg"
class="form-control"
from="${['png':'png', 'jpg':'jpg', 'jpeg':'jpeg']}"
optionKey="key" optionValue="value" />

</div>
</div></td>
<td><div class="form-group">
<div class="col-sm-12">
<div class='input-group date' id='dateDocumentAddeddiv'>
<input type="text" id='dateCreated' class="form-control"
name="caseDocumentInstance.dateCreated"
value="<g:formatDate format="MM/dd/yyyy"
date="${caseDocumentInstance?.dateCreated}"/>"
placeholder="mm/dd/yyyy"> <span
class="input-group-addon"> <span
class="glyphicon glyphicon-calendar"></span>
</span>
</div>
</div>

</div></td>
<td><div class="form-group">
<div class="col-sm-12">
<input type="text" id='caption' class="form-control"
name="caption" value="${caseDocumentInstance?.caption}" />
</div>

</div></td>
<td><div class="form-group">
<div class="col-sm-12">
<input type="text" id='comments' class="form-control"
name="comments" value="${caseDocumentInstance?.comments}" />
</div>

</div></td>

<td height="50px"><div class="form-group">
<div class="col-sm-12">
<button type="submit" id="imageaddbutton"
class="btn btn-md btn-success">Add</button>
</div>
</div></td>
</tr>
</tbody>
</table>
</form>

3. Data table on which added image is listed:
<table id="tableaddedimages"
class="table table-striped table-bordered table-hover"
style="width: 100%">
<thead>
<tr>
<th width="1%"></th>
<th width="9%"></th>
<th width="25%">Image</th>
<th width="10%">Image Type</th>
<th width="10%">Date Added</th>
<th width="10%">Attach To Report</th>
<th width="10%">Show In Report</th>
<th width="17%">Comments</th>
<th width="13%">Caption</th>
<th width="5%"></th>
</tr>
</thead>
<tbody>

</tbody>
</table>
</div>
<script type="text/javascript">
var getsaveURL = "${createLink(controller:'caseDocuments', action:'save')}";
var getdeleteURL =
"${createLink(controller:'caseDocuments',action:'delete')}";

if("${caseInfoInstance?.statusFlag}"==="finalized"){
$('#imgdeletebutton').prop('disabled',true);
$('button').hide();
}


$( document).on( "click", "#imgdeletebutton", function(e){
    var tableaddedimages = $('#tableaddedimages').DataTable();
    var aData=  tableaddedimages.row('.selected').data();
  var id = aData[0];
//alert ("caseDocumentID:" + id);
  $("#confirmimgbody").html("Are you sure you want to delete ?");
$('#confirm-img-delete').data('caseDocumentID', id).modal('show');
});
$( document).on( "click", "#imgdelete", function(e){
$('#confirm-img-delete').modal('hide');
var caseDocumentID = $('#confirm-img-delete').data('caseDocumentID');
$.ajax({
        url: getdeleteURL,
        type:"post",
        dataType: 'json',
        data: {caseDocumentID: caseDocumentID},
        success: function(data) {
        reloadImageTable();
        },
        statusCode: {
            403: function() {
            on403();
            }
        }
    });
});

$('#tableaddedimages tbody').on( 'click', 'tr', function () {
    var tableaddedimages = $('#tableaddedimages').DataTable();
         tableaddedimages.$('tr.selected').removeClass('selected');
         $(this).addClass('selected');
});

function handleImgClick(imageId) {

$.ajax({
           url: '${createLink (controller:'caseImages',
action:'getImage')}',
           type:"post",
           data: {imageId: imageId},
           success: function(data) {

$('#attachedImageModal').find('[id="caseDocumentID"]').val(imageId);
//$('#attachedImageModal').find('[id="imgNameDivOnModal"]').html(data.imgName);
$('#attachedImageModal').find('[id="attachedImgOnModal"]').attr('src',
data);
$("#attachedImageModal").modal("show");
           },
           error: function(xhr, statusText, err){
               alert("Error:" + xhr.status);
           }

            });
}
$(document).ready(function() {
var caseID = $('#caseID').val();
var caseDocumentID = $('#caseDocumentID').val();
var userTimeZone=Intl.DateTimeFormat().resolvedOptions().timeZone
var tableaddedimages = $('#tableaddedimages').DataTable({
    "bProcessing": true,
    "sDom": '',
    paging: false,
    "bDeferRender": true,
    "sAjaxSource":'${createLink (controller:'caseImages',
action:'caseImagesList')}',
    "fnServerParams": function ( aoData ) {
        aoData.push( { "name": "caseID", "value": caseID });
        aoData.push( { "name": "caseDocumentID", "value": caseDocumentID });
        aoData.push( { "name": "userTimeZone", "value": userTimeZone });
   },
   "fnServerData": function ( sSource, aoData, fnCallback ) {
$.getJSON( sSource, aoData, function (json) {
/* Do whatever additional processing you want on the callback, then tell
DataTables */
fnCallback(json);
});
 },

   "columnDefs": [
                { "targets": [0 ], "visible": false, "searchable":
false,"orderable": false, "bSortable": false},
                  { "targets": [1 ], "visible": false, "searchable":
false,"orderable": false, "bSortable": false},
      { "targets": [2 ],  "render": function ( data, type, row ){
      return  "<form><input type=\"hidden\" name=\"caseDocumentID\"
value="+row[1]+" ><a href=\"#\" onclick=\"handleImgClick(" + row[1] + ");\"
>"+row[2]+"</a></form>" ;
              }
              },
                { "targets": [5], "bSortable": false,  "render": function (
data, type, row ) {
              var attachToReport = row[5];
                    var checked = '';
              if (attachToReport) checked = 'checked';
                       if ("${caseInfoInstance?.statusFlag}"==="finalized")
                   { //disable checkbox
                    checked+= ' disabled';
                   }
                       var field = "<div class=\"checkbox\"
style=\"float:left; height: 14px; line-height: 14px; padding-right: 10px;
margin-top: -5px;\"><label><input name=\"attachToReport\" type=\"checkbox\"
onclick=\"handleClickDoc(this,"+ row[1]+ ")\" class=\"checkbox1
colored-blue\" ' "+checked+"><span class=\"text\"></span></label></div>";
                   return field ;
                       }
                  },
                  { "targets": [6], "bSortable": false,  "render": function
( data, type, row ) {
            var showInReport = row[6];
                  //alert(showInReport);
              var checked = '';
              if (showInReport) checked = 'checked';
            if ("${caseInfoInstance?.statusFlag}"==="finalized")
            { //disable checkbox
            checked+= ' disabled';
                }
        var field = "<div class=\"checkbox\" style=\"float:left; height:
14px; line-height: 14px; padding-right: 10px; margin-top:
-5px;\"><label><input name=\"showInReport\" type=\"checkbox\"
onclick=\"handleClickShowReport(this,"+ row[1]+ ")\" class=\"checkbox1
colored-blue\" ' "+checked+"><span class=\"text\"></span></label></div>";
                  return field ;
                  }
                  },
                  { "targets": [7], "bSortable": false,  "render": function
( data, type, row ) {
      if ("${caseInfoInstance?.statusFlag}"==="finalized")
      {
      return  " <div class='form-inline'> </div>";
      }
          return  " <div class='form-inline'>" + row[7] + "</div>";

                }
                  },
              { "targets": [8], "bSortable": false,  "render": function (
data, type, row ) {
      if ("${caseInfoInstance?.statusFlag}"==="finalized")
      {
      return  " <div class='form-inline'> </div>";
      }
          return  " <div class='form-inline'>" + row[6] + "</div>";
            }
              },


4. On click, we show the image from db to dialog:

<div class="modal fade" id="attachedImageModal" tabindex="-1" role="dialog"
aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog modal-lg" role="document">
<div class="modal-content">
<div class="modal-header" id="imgNameDivOnModal" align="center"></div>
<div class="modal-body">
<div style="position:relative" align="center">
      <div id="imgdiv" style="text-align: center;">
      <input type="hidden" id="caseDocumentID" />
<img id="attachedImgOnModal" style="border: 10px solid #ccc; padding:20px;"
width="80%" src=""/>
<br/>
<button id="toggleEdit">Edit</button> <button
id="clearMarkers">Clear</button> <button id="saveImg">Save</button> <button
id="DownloadImg">Download</button>
</div>
<div id=txt></div>
      </div>
</div>
<div class="modal-footer">
<button type="button" class="btn btn-default"
data-dismiss="modal">OK</button>
</div>
</div>
</div>
</div>


4. Now on this dialog: I am adding imgNotes and this gives 403 error:

$(document).ready(function() {
$("#attachedImgOnModal").imgNotes({
onAdd: function() {
this.options.vAll = "bottom";
this.options.hAll = "middle";
elem = $(document.createElement('div'))
      .css({width:'27px',
height:'40px','text-align':'center',color:'#fff','font-weight':'bold',
'font-size':'14px'})
      .append($('<p>'+this.noteCount+'</p>').css({'z-index':1,
position:'relative', top:'-8px'}))
      .prepend($('<img>',{src:
'${resource(dir:'images',file:'marker_black.png')}', width:'27px',
height:'40px'}).css({position:'relative', top:'0px', left:'0px'}));
return elem;
}
});

if ($("#attachedImgOnModal").imgNotes("option","canEdit", true)) {
$("#toggleEdit").text("View");
} else {
$("#toggleEdit").text("Edit");
}


});


5. Attached is the error shown.

Thanks,
Ritika

**Comment by waynegm** [comment] 2016-11-14 11:27
Can you confirm that there is a "marker_black.png" file in your "images" directory as referred to in your custom "onAdd" callback. 

Since you are directly inserting the image and applying your own css there is no need to include the css that comes with the default implementation at the top of the file, ie 
```
<link rel="stylesheet" href="${resource(dir:'css',file:'marker.css')}" /> 
```

Wayne

**Comment by ritikajagtiani** [comment] 2016-11-14 12:58
Hi Wayne,

Yes marker_black.png is in my png folder. Again I took the imgNotes code
from basic_interactive.html in your given examples.

Regarding css, I removed and checked, I still get 403.

Thanks,
Ritika Jagtiani

**Comment by waynegm** [comment] 2016-11-15 10:26
I think the problem is there is no image to show when you create the imgNotes instance in the $(document).ready function. You need to adjust your logic so that the imgNotes instance is created after the image with id "attachedImgOnModal" has a url/file assigned to its "src" attribute.

**Comment by ritikajagtiani** [comment] 2016-11-15 16:07
Ok. Sure, I will try that.
Will let you know if that succeeds.
Thank you.

-Ritika

**Closed** 2016-12-03 04:21 UTC
